---
- name: Assert smb_client_state
  ansible.builtin.assert:
    that: >-
      {{ smb_client_state is defined and smb_client_state is string
      and smb_client_state in ['present', 'absent'] }}
    quiet: true

- name: Assert smb_client_credentials is array
  ansible.builtin.assert:
    that: >-
      {{ smb_client_credentials is defined
      and smb_client_credentials | type_debug == 'list' }}
    quiet: true

- name: Assert smb_client_credentials name
  ansible.builtin.assert:
    that: >-
      {{ item.name is defined and item.name is string and item.name != "" }}
    quiet: true
  loop: "{{ smb_client_credentials }}"
  no_log: true

- name: Assert smb_client_credentials name are unique
  ansible.builtin.assert:
    that: >-
      {{ smb_client_credentials | length ==
      smb_client_credentials | map(attribute='name') | unique | length }}
    quiet: true
  when: smb_client_credentials | length > 0

- name: Assert smb_client_credentials state
  ansible.builtin.assert:
    that: >-
      {{ item.state is undefined or (
        item.state is defined and item.state in ['present', 'absent']) }}
    quiet: true
  loop: "{{ smb_client_credentials }}"
  no_log: true
